name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install boost
      run: sudo apt-get install libboost-all-dev
    - name: install glfw
      run: sudo apt-get install libglfw3-dev
    - name: install vulkan
      run: sudo apt-get install libvulkan1
    - name: install python-pip
      run: sudo apt-get install python-pip
    - name: install cpplint
      run: sudo pip install cpplint
    - name: cpplint test
      run: cpplint --recursive ../
    - name: cmake
      run: cmake ./
    - name: make
      run: make
